"""delete views test

Revision ID: 1c006f4a7e60
Revises: 1d6e3a35bb7c
Create Date: 2024-11-10 14:19:28.177987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c006f4a7e60'
down_revision = '1d6e3a35bb7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
