"""Added a profile column to UserAccount

Revision ID: 1edc43cefa2b
Revises: 
Create Date: 2024-10-30 03:42:03.701521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edc43cefa2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.Enum('admin', 'seller', 'buyer', 'usedCarAgent', name='profile_type'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###
